# Generated by Django 5.1.4 on 2024-12-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_movie_director_remove_movie_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Music',
        ),
    ]
