# Generated by Django 5.1.4 on 2024-12-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='type',
            new_name='sport_type',
        ),
    ]
