# Generated by Django 5.1.4 on 2024-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_rename_name_sport_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='date',
            field=models.DateField(),
        ),
    ]
